bot:
  discord:
    token: DISCORD_TOKEN

commands:
  - name: cost
    type: slash
    webhook: "https://n8n.local/webhooks/submit-cost"
    fields:
      - name: company
        type: select
        options: ["Company A", "Company B"]
        required: true
      - name: pdf
        type: attachment
        required: true
      - name: title
        type: text
        required: true
      - name: amount
        type: text
        required: true
      - name: payment
        type: text
        required: false
      - name: month
        type: select
        options: ["January", "February"]
        required: true
  - name: remote-test
    type: slash
    webhook: "https://httpbin.org/post"
    fields:
      - name: department
        type: remote_select
        webhook: "https://jsonplaceholder.typicode.com/users"
        required: true
      - name: description
        type: text
        required: true
  - name: feedback
    type: modal
    webhook: "https://httpbin.org/post"
    fields:
      - name: name
        type: text
        required: true
      - name: email
        type: text
        required: true
      - name: rating
        type: text
        required: true
      - name: comments
        type: text
        required: false